[CmdletBinding()]
param([Parameter(Mandatory = $true)][switch]$ConfirmDemo)
$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
$ExpectedPSHome = "C:\Windows\System32\WindowsPowerShell\v1.0"
if (-not [Environment]::Is64BitProcess -or $PSVersionTable.PSEdition -ne "Desktop" -or [IO.Path]::GetFullPath($PSHOME) -cne $ExpectedPSHome -or [IO.Path]::GetFullPath((Join-Path $PSHOME "powershell.exe")) -cne (Join-Path $ExpectedPSHome "powershell.exe") -or [IO.Path]::GetFullPath([Diagnostics.Process]::GetCurrentProcess().MainModule.FileName) -cne (Join-Path $ExpectedPSHome "powershell.exe")) { throw "Super1 smoke requires the trusted 64-bit Windows PowerShell host." }
if (-not $ConfirmDemo) { throw "Demo smoke requires -ConfirmDemo." }
if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { throw "Super1 smoke requires an elevated Administrator shell." }
$Root = "C:\Super1"; $App = Join-Path $Root "app"; $Deploy = Join-Path $App "deploy"
$TrustedScript = [IO.Path]::GetFullPath((Join-Path $Deploy "run_super1_demo_smoke_windows.ps1")); if ([IO.Path]::GetFullPath($PSCommandPath) -cne $TrustedScript) { throw "Smoke wrapper path is not the exact trusted app path." }
$TrustedModules = Join-Path $ExpectedPSHome "Modules"; $ScheduledTasksModule = [IO.Path]::GetFullPath((Join-Path $TrustedModules "ScheduledTasks\ScheduledTasks.psd1")); $OriginalPSModulePath = $env:PSModulePath; $env:PSModulePath = $TrustedModules
$TrustedTaskHelper = [IO.Path]::GetFullPath((Join-Path $Deploy "super1_secure_task.ps1")); if (-not (Test-Path -LiteralPath $TrustedTaskHelper -PathType Leaf) -or (Get-Item -LiteralPath $TrustedTaskHelper -Force).Attributes -band [IO.FileAttributes]::ReparsePoint) { throw "Trusted secure task helper is missing or unsafe." }; $loadedScheduledTasks = Import-Module -Name $ScheduledTasksModule -Force -PassThru -ErrorAction Stop; $Module = $loadedScheduledTasks; if ([IO.Path]::GetFullPath($Module.Path) -cne $ScheduledTasksModule) { throw "Unexpected ScheduledTasks module path." }; $ModulePath = $Module.Path; . $TrustedTaskHelper
$MainTask = "Super1XM"; $WatchdogTask = "Super1Watchdog"; $State = Join-Path $Root "state"; $Archive = Join-Path $Root "archive"; $Control = Join-Path $Root "probe-control"; $launcher = Join-Path $Deploy "run_super1_windows.ps1"
$RunnerSid = [string](Assert-Super1SecureTaskBindings -Root $Root -MainTask $MainTask -WatchdogTask $WatchdogTask)
if ($RunnerSid -notmatch '^S-1-5-21-' -or $RunnerSid -in @([string][Security.Principal.WindowsIdentity]::GetCurrent().User.Value, "S-1-5-18", "S-1-5-32-544")) { throw "Invalid task-bound Super1 runner SID." }
$runId = [Guid]::NewGuid().ToString("N"); $nonce = [Guid]::NewGuid().ToString("N"); $transaction = Join-Path $Archive ("readiness-" + $runId); $output = Join-Path $transaction "output"; $requestPath = Join-Path $transaction "request.json"; $resultPath = Join-Path $output "result.json"; $producerPath = Join-Path $output "producer.json"; $activeRequest = Join-Path $Control "active.json"
$mainXml = Get-Super1SecureTaskXml -TaskName $MainTask; $watchdogXml = Get-Super1SecureTaskXml -TaskName $WatchdogTask; $success = $false; $transactionRequestEvidence = $null; $activeRequestEvidence = $null; $cleanupErrors = New-Object Collections.Generic.List[string]
try {
    Assert-Super1SecureDirectoryAcl -Path $Archive; Assert-Super1SecureDirectoryAcl -Path $Control
    New-Super1SecureDirectory -Path $transaction -RunnerSid $RunnerSid | Out-Null; New-Super1SecureDirectory -Path $output -RunnerSid $RunnerSid -RunnerRights ([Security.AccessControl.FileSystemRights]::Modify) | Out-Null
    $mainBackup = New-Super1SecureLockedFile -Path (Join-Path $transaction "main.xml") -Content ($mainXml + [Environment]::NewLine) -RunnerSid $RunnerSid; $mainBackup.lock.Dispose()
    $watchdogBackup = New-Super1SecureLockedFile -Path (Join-Path $transaction "watchdog.xml") -Content ($watchdogXml + [Environment]::NewLine) -RunnerSid $RunnerSid; $watchdogBackup.lock.Dispose()
    if (Test-Path -LiteralPath $activeRequest) { throw "Super1 active request already exists." }
    Stop-Super1SecureRuntime -Root $Root -MainTask $MainTask -WatchdogTask $WatchdogTask; Assert-Super1SecureStopped -Root $Root -MainTask $MainTask -WatchdogTask $WatchdogTask
    $flat = (& (Join-Path $Deploy "check_super1_flat_windows.ps1") -KeepStopped | Select-Object -Last 1 | ConvertFrom-Json); if ([string]$flat.state -cne "READY_FLAT_SEALED") { throw "Sealed pre-flat check failed." }
    $requestedAt = [DateTimeOffset]::UtcNow; $launcherSha256 = [string](Get-Super1SecureSha256 -Path $launcher); $requestPayload = [ordered]@{ schema_version = 1; kind = "smoke"; transaction_id = $runId; nonce = $nonce; requested_at_utc = $requestedAt.ToString("o"); expected_runner_sid = $RunnerSid; expected_launcher_sha256 = $launcherSha256; result_path = $resultPath; producer_path = $producerPath; request_path = $requestPath }; $requestJson = $requestPayload | ConvertTo-Json -Compress
    $transactionRequestEvidence = New-Super1SecureLockedFile -Path $requestPath -Content ($requestJson + [Environment]::NewLine) -RunnerSid $RunnerSid; $activeRequestEvidence = New-Super1SecureLockedFile -Path $activeRequest -Content ($requestJson + [Environment]::NewLine) -RunnerSid $RunnerSid
    Start-ScheduledTask -TaskName $MainTask; $deadline = [DateTimeOffset]::UtcNow.AddSeconds(120)
    do { $mainState = [string](Get-ScheduledTask -TaskName $MainTask).State; $watchdogState = [string](Get-ScheduledTask -TaskName $WatchdogTask).State; if ($mainState -notin @("Running", "Queued") -and $watchdogState -notin @("Running", "Queued") -and (Test-Path -LiteralPath $resultPath)) { break }; if ([DateTimeOffset]::UtcNow -ge $deadline) { throw "Super1 smoke task timed out." }; Start-Sleep -Seconds 1 } while ($true)
    Stop-Super1SecureRuntime -Root $Root -MainTask $MainTask -WatchdogTask $WatchdogTask; Assert-Super1SecureStopped -Root $Root -MainTask $MainTask -WatchdogTask $WatchdogTask
    if ([int](Get-ScheduledTaskInfo -TaskName $MainTask).LastTaskResult -ne 0) { throw "Super1 smoke LastTaskResult was not 0." }
    if ((Get-Super1SecureTaskXml -TaskName $MainTask) -cne $mainXml -or (Get-Super1SecureTaskXml -TaskName $WatchdogTask) -cne $watchdogXml) { throw "Super1 task XML changed during smoke." }
    $transactionRequestEvidence.lock.Dispose(); $transactionRequestEvidence = $null; $activeRequestEvidence.lock.Dispose(); $activeRequestEvidence = $null; Remove-Item -LiteralPath $activeRequest -Force
    Seal-Super1SecureEvidenceTree -Path $transaction
    $producer = Get-Super1SecureProducerEnvelope -ProducerPath $producerPath -RequestPath $requestPath -ResultPath $resultPath -TransactionId $runId -Nonce $nonce -Kind "smoke" -RunnerSid $RunnerSid -ExpectedLauncherPath $launcher -ExpectedLauncherSha256 $launcherSha256 -ExpectedExitCode 0 -NotBefore $requestedAt
    if (-not (Test-Path -LiteralPath $resultPath -PathType Leaf) -or -not (Test-Path -LiteralPath $producerPath -PathType Leaf)) { throw "Smoke result or producer is missing." }
    $resultHash = [string]$producer.result_sha256; if ($resultHash -cne [string]$producer.result_sha256) { throw "Smoke result hash does not match producer envelope." }; $result = $producer.result_payload; if ([string]$result.state -cne "PASS" -or $result.demo_verified -ne $true -or [string]$result.cancelled.state -cne "CANCELLED" -or [int]$result.open_orders_after -ne 0 -or [int]$result.open_positions_after -ne 0 -or [int]$result.unknown_exposure_after -ne 0) { throw "Smoke acceptance criteria failed." }
    $postFlat = (& (Join-Path $Deploy "check_super1_flat_windows.ps1") -KeepStopped | Select-Object -Last 1 | ConvertFrom-Json); if ([string]$postFlat.state -cne "READY_FLAT_SEALED") { throw "Sealed post-flat check failed." }
    $restartStarted = [DateTimeOffset]::UtcNow; Start-ScheduledTask -TaskName $MainTask; $healthDeadline = [DateTimeOffset]::UtcNow.AddSeconds(90); do { $healthPath=Join-Path $State "health.json"; $healthPayload=if(Test-Path $healthPath){Get-Content -Raw $healthPath|ConvertFrom-Json}else{$null}; if ((Get-ScheduledTask -TaskName $MainTask).State -eq "Running" -and (Test-Path $healthPath) -and (Get-Item $healthPath).LastWriteTimeUtc -ge $restartStarted.UtcDateTime -and [string]$healthPayload.updated_at -and [DateTimeOffset]::Parse([string]$healthPayload.updated_at) -ge $restartStarted -and [string]$healthPayload.state -eq "RUNNING") { break }; if ([DateTimeOffset]::UtcNow -ge $healthDeadline) { throw "Fresh main health was not observed." }; Start-Sleep -Seconds 1 } while ($true); $healthCheckedAt = [DateTimeOffset]::UtcNow
    $watchdogRestartStarted = [DateTimeOffset]::UtcNow; Start-ScheduledTask -TaskName $WatchdogTask; $watchdogDeadline = [DateTimeOffset]::UtcNow.AddSeconds(90); do { $watchdogPath=Join-Path $Root "watchdog_status.json"; $watchdogRecord = if(Test-Path $watchdogPath){Get-Content -Raw $watchdogPath | ConvertFrom-Json}else{$null}; if ((Get-ScheduledTask -TaskName $WatchdogTask).State -eq "Running" -and (Test-Path $watchdogPath) -and (Get-Item $watchdogPath).LastWriteTimeUtc -ge $watchdogRestartStarted.UtcDateTime -and [string]$watchdogRecord.observed_at_utc -and [DateTimeOffset]::Parse([string]$watchdogRecord.observed_at_utc) -ge $watchdogRestartStarted -and [string]$watchdogRecord.state -eq "HEALTHY" -and [string]$watchdogRecord.main_task -ceq $MainTask) { break }; if ([DateTimeOffset]::UtcNow -ge $watchdogDeadline) { throw "Fresh watchdog health was not observed." }; Start-Sleep -Seconds 1 } while ($true); $watchdogCheckedAt = [DateTimeOffset]::UtcNow
    if (-not (Test-Path (Join-Path $State "campaign_lock.json")) -or (Test-Path (Join-Path $State "fatal_latch.json")) -or (Test-Path (Join-Path $State "launcher_failure.json"))) { throw "Campaign lock/fatal-latch/launcher-failure contract failed." }
    $finalRunnerSid = [string](Assert-Super1SecureTaskBindings -Root $Root -MainTask $MainTask -WatchdogTask $WatchdogTask); if ($finalRunnerSid -cne $RunnerSid -or (Get-Super1SecureTaskXml -TaskName $MainTask) -cne $mainXml -or (Get-Super1SecureTaskXml -TaskName $WatchdogTask) -cne $watchdogXml) { throw "Super1 task bindings or XML changed after smoke." }
    $success = $true; [ordered]@{ state = [string]$result.state; demo_verified = [bool]$result.demo_verified; cancelled = $result.cancelled; open_orders_after = [int]$result.open_orders_after; open_positions_after = [int]$result.open_positions_after; unknown_exposure_after = [int]$result.unknown_exposure_after; pre_flat_evidence = [string]$flat.evidence_path; smoke_evidence = $transaction; post_flat_evidence = [string]$postFlat.evidence_path; result_sha256 = $resultHash; producer_sha256 = $producer.producer_sha256; health_checked_at = $healthCheckedAt.ToString("o"); watchdog_checked_at = $watchdogCheckedAt.ToString("o") } | ConvertTo-Json -Depth 8
}
catch { $originalException = $_; try { if ($transactionRequestEvidence) { $transactionRequestEvidence.lock.Dispose(); $transactionRequestEvidence=$null }; if ($activeRequestEvidence) { $activeRequestEvidence.lock.Dispose(); $activeRequestEvidence=$null }; if (Test-Path -LiteralPath $activeRequest) { Remove-Item -LiteralPath $activeRequest -Force -ErrorAction SilentlyContinue }; Stop-Super1SecureRuntime -Root $Root -MainTask $MainTask -WatchdogTask $WatchdogTask -ErrorAction SilentlyContinue; Assert-Super1SecureStopped -Root $Root -MainTask $MainTask -WatchdogTask $WatchdogTask; if (Test-Path -LiteralPath $transaction) { Seal-Super1SecureEvidenceTree -Path $transaction; Assert-Super1SecureSealedTree -Path $transaction }; Assert-Super1SecureTaskBindings -Root $Root -MainTask $MainTask -WatchdogTask $WatchdogTask | Out-Null } catch { $cleanupErrors.Add($_.Exception.Message) }; if ($cleanupErrors.Count) { throw "$($originalException.Exception.Message); cleanup: $($cleanupErrors -join '; ')" }; throw $originalException }
finally { if ($transactionRequestEvidence) { $transactionRequestEvidence.lock.Dispose() }; if ($activeRequestEvidence) { $activeRequestEvidence.lock.Dispose() }; $env:PSModulePath = $OriginalPSModulePath; if (-not $success) { try { Stop-Super1SecureRuntime -Root $Root -MainTask $MainTask -WatchdogTask $WatchdogTask -ErrorAction SilentlyContinue } catch {} } }
